#!/bin/sh

# Function to copy files and remove unnecessary ones
copy_files() {
  sudo cp ../files -r "$1"
  cd "$1"/files || exit 1
  sudo rm -r install uninstall README.md LICENSE
}

# Check if the .git directory exists and delete it if found
[ -d ".git" ] && sudo rm -r .git

case "$1" in
  arch)
    copy_files "/srv/http"
    echo "Success !"
    ;;
  debian)
    copy_files "/var/www/html"
    echo "Success !"
    ;;
  *)
    echo "Usage: $0 arch|debian" >&2
    exit 1
    ;;
esac
